// <auto-generated />
using System.Collections.Generic;
using DotNet_Test_TTSS.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DotNet_Test_TTSS.Migrations
{
    [DbContext(typeof(SupabaseDbContext))]
    [Migration("20250613072406_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DotNet_Test_TTSS.Models.Area", b =>
                {
                    b.Property<string>("AreaId")
                        .HasColumnType("text")
                        .HasColumnName("area_id");

                    b.Property<Dictionary<string, int>>("RequiredResources")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("required_resources");

                    b.Property<int>("TimeConstraintHours")
                        .HasColumnType("integer")
                        .HasColumnName("time_constraint");

                    b.Property<int>("UrgencyLevel")
                        .HasColumnType("integer")
                        .HasColumnName("urgency_level");

                    b.HasKey("AreaId");

                    b.ToTable("areas1", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
